### Register Request ###
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Sachithra",
  "password": "kavi",
  "email": "Sachithra@gmail.com"
}


### Login Request ###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "exampleUser",
  "password": "examplePassword"
}

